DISTRO_INITSCRIPTS = "initscripts-shr"
DISTRO_DEV_MANAGER = "udev"

PREFERRED_PROVIDER_frameworkd-config = "frameworkd-config-shr"
PREFERRED_PROVIDER_frameworkd = "frameworkd"
PREFERRED_PROVIDER_gpsd = "fso-gpsd"

PREFERRED_VERSION_shared-mime-info = "0.51"
PREFERRED_VERSION_navit = "0.1.0+svnrev${SRCREV}"
PREFERRED_VERSION_libosip2 = "2.2.2"
PREFERRED_VERSION_udev = "124"
PREFERRED_VERSION_midori = "0.1.2"

#FSO stuff
SRCREV_pn-frameworkd = "65ebcc86e85980827925588753f47bebf6d4a96e"
SRCREV_pn-frameworkd-config-shr = "65ebcc86e85980827925588753f47bebf6d4a96e"
SRCREV_pn-fso-gpsd = "${AUTOREV}"
SRCREV_pn-fso-sounds = "${AUTOREV}"
SRCREV_pn-gsm0710muxd = "${AUTOREV}"
SRCREV_pn-gsmd2 = "${AUTOREV}"
SRCREV_pn-illume-theme-freesmartphone = "${AUTOREV}"
SRCREV_pn-mickeydbus = "${AUTOREV}"
SRCREV_pn-mickeyterm = "${AUTOREV}"
SRCREV_pn-python-pytrc = "${AUTOREV}"
SRCREV_pn-zhone = "${AUTOREV}"

#SHR stuff
SRCREV_pn-libhito = "${AUTOREV}"
SRCREV_pn-neod = "${AUTOREV}"
SRCREV_pn-shr-settings = "7ba3c4c6778cf2a54a34cb044527de890557c4f8"
SRCREV_pn-shr-theme = "4613a89ffa96d9a858e773719d510c612b1593a7"
SRCREV_pn-libframeworkd-glib = "37b46d8565505c0ec92b921866cd2fd7fe927706"
SRCREV_pn-ophonekitd = "4613a89ffa96d9a858e773719d510c612b1593a7"
SRCREV_pn-openmoko-messages3 = "4613a89ffa96d9a858e773719d510c612b1593a7"
SRCREV_pn-openmoko-contacts3 = "4613a89ffa96d9a858e773719d510c612b1593a7"
SRCREV_pn-openmoko-dialer3 = "4613a89ffa96d9a858e773719d510c612b1593a7"
SRCREV_pn-libframeworkd-phonegui-efl = "4613a89ffa96d9a858e773719d510c612b1593a7"
SRCREV_pn-libframeworkd-phonegui = "4613a89ffa96d9a858e773719d510c612b1593a7"
SRCREV_pn-libframeworkd-phonegui-gtk = "${AUTOREV}"
SRCREV_pn-pyphonelog = "${AUTOREV}"
SRCREV_pn-shr-theme-brave = "${AUTOREV}"

#General stuff
EFL_SRCREV = "38274"

SRCREV_pn-navit = "1981"
SRCREV_pn-python-elementary = "38899"
SRCREV_pn-omview = "${AUTOREV}"
SRCREV_pn-pythm = "${AUTOREV}"
SRCREV_pn-omoney = "29"
SRCREV_pn-enotes = "19"
SRCREV_pn-ebrainy = "${AUTOREV}"

