#!/bin/bash

bail_out()
{
	echo "$2"
	exit $1
}

[ "$(basename $PWD)" == "openembedded" ] || bail_out 1 "do-patch must be called from inside openembedded"
[ -d ../shr/patches ] || bail_out 0 "nothing to patch"

CURHEAD=$(git rev-parse HEAD)
[ -e .patched -a "$CURHEAD" == "$(cat .patched)" ] && bail_out 0 "openembedded is already patched"

for d in ../shr/patches/*; do
	[ -d "$d" ] || continue
	echo "applying $(basename $d) patches"
	for p in $(ls "$d"/* | sort); do
		git apply $p
	done
done

echo $CURHEAD > .patched
		
